import 'server-only'
import { eq } from 'drizzle-orm'
import { db } from '@/db'
import { organization } from '@/db/schema'
import type { AuthContext } from '@/auth/context'

// H3 (Ontario PIPEDA): AI report drafting sends student data to a cross-border LLM provider
// (REPORT_PROVIDER=anthropic → US; minimax → api.minimaxi.com → CN). Before the FIRST draft in an
// organization we capture a one-time, org-level acknowledgment that this cross-border processing is
// understood. Combined with prompt-boundary name redaction (report-prompt.ts redactStudentData), this
// closes the "sharpest exposure": no real minor name leaves the jurisdiction, and the org explicitly
// acknowledged the transfer.
//
// STORAGE: the EXISTING organization.metadata JSON text column (Better-Auth-managed). No migration —
// and auth-schema.ts is regenerated by `auth:generate`, so a NEW column there would be clobbered. We
// merge into whatever metadata already holds so other keys are never lost.

const ACK_KEY = 'aiCrossBorderAckAt'
const ACK_BY_KEY = 'aiCrossBorderAckBy'

// Thrown by the report core when an org has not yet acknowledged cross-border AI processing. The
// report Server Action catches core errors and returns them as data (actions.ts), so this reaches the
// client intact (unlike a thrown-out-of-action error, which prod redaction would blank out).
export class CrossBorderAiAckRequiredError extends Error {
  constructor() {
    super('CROSS_BORDER_AI_ACK_REQUIRED')
    this.name = 'CrossBorderAiAckRequiredError'
  }
}

// Pure JSON helpers (no DB) — directly unit-testable.
export function parseCrossBorderAck(metadata: string | null): Date | null {
  if (!metadata) return null
  try {
    // JSON.parse 可返回任意 JSON 值（字符串/数字/数组…），不能盲 cast 成对象。先运行时收窄，
    // 与 withCrossBorderAck 的解析保持一致。
    const parsed: unknown = JSON.parse(metadata)
    if (!parsed || typeof parsed !== 'object' || Array.isArray(parsed)) return null
    const v = (parsed as Record<string, unknown>)[ACK_KEY]
    if (typeof v !== 'string') return null
    const d = new Date(v)
    return Number.isNaN(d.getTime()) ? null : d
  } catch {
    return null
  }
}

export function withCrossBorderAck(metadata: string | null, at: Date, by: string): string {
  let obj: Record<string, unknown> = {}
  if (metadata) {
    try {
      const parsed = JSON.parse(metadata)
      // Merge so we never clobber other metadata keys. Corrupt/non-object metadata → start fresh
      // rather than crash (never lose the ack over bad prior data).
      if (parsed && typeof parsed === 'object' && !Array.isArray(parsed)) {
        obj = parsed as Record<string, unknown>
      }
    } catch {
      obj = {}
    }
  }
  obj[ACK_KEY] = at.toISOString()
  obj[ACK_BY_KEY] = by
  return JSON.stringify(obj)
}

// organization is a Better-Auth table (the tenant itself), not a tenant-scoped app table, so it is
// read/written via the raw db handle by ctx.tenantId — NOT through forTenant() (which is for tables
// carrying a tenant_id column).
async function readOrgMetadata(ctx: AuthContext): Promise<string | null> {
  const [org] = await db
    .select({ metadata: organization.metadata })
    .from(organization)
    .where(eq(organization.id, ctx.tenantId))
    .limit(1)
  return org?.metadata ?? null
}

export async function getCrossBorderAiAck(ctx: AuthContext): Promise<Date | null> {
  return parseCrossBorderAck(await readOrgMetadata(ctx))
}

export async function requireCrossBorderAiAck(ctx: AuthContext): Promise<void> {
  if (!(await getCrossBorderAiAck(ctx))) throw new CrossBorderAiAckRequiredError()
}

export async function acknowledgeCrossBorderAiCore(ctx: AuthContext): Promise<void> {
  // organization.metadata 是单一共享 JSON 列，withCrossBorderAck 会 merge 进读到的旧值。裸读-改-写
  // 在并发写入下会丢更新（后提交者覆盖前者对 metadata 任意键的改动）。用事务 + SELECT ... FOR UPDATE
  // 锁住该行：并发写者串行等待并在拿锁后重读到已 ack 的值 → 命中幂等短路，不会互相覆盖。
  await db.transaction(async (tx) => {
    const [org] = await tx
      .select({ metadata: organization.metadata })
      .from(organization)
      .where(eq(organization.id, ctx.tenantId))
      .limit(1)
      .for('update')
    const current = org?.metadata ?? null
    if (parseCrossBorderAck(current)) return // idempotent: already acknowledged
    const next = withCrossBorderAck(current, new Date(), ctx.userId)
    await tx.update(organization).set({ metadata: next }).where(eq(organization.id, ctx.tenantId))
  })
}
