// eslint-config-next@16 ships NATIVE flat configs — spread them directly.
// (Using FlatCompat.extends('next/...') triggers a circular-structure crash in
// ESLint 9's eslintrc validator against Next 16's flat config, so we import the
// flat arrays instead. Same rule sets: next/core-web-vitals + next/typescript.)
import nextCoreWebVitals from 'eslint-config-next/core-web-vitals'
import nextTypescript from 'eslint-config-next/typescript'

const eslintConfig = [
  {
    ignores: [
      '.next/**',
      'node_modules/**',
      'drizzle/**',
      'dist/**',
      'coverage/**',
      'next-env.d.ts',
      // Generated by the Better Auth CLI — do not lint.
      'src/db/auth-schema.ts',
    ],
  },
  ...nextCoreWebVitals,
  ...nextTypescript,
]

export default eslintConfig
